mahoshojo:
  ema:
    full_name: 樱羽艾玛
    emotion_count: 8
    font: font3.ttf
    "无感情": [2,3]
    "愤怒": [1,3]
    "嫌弃": [5]
    "疑惑": [5]
    "惊讶": [7]
    "伤心": [5]
    "害羞": [4,8]
    "开心": [2,6]
    "恐惧": [5]
    "无语": [5,3]
    "大笑": [6]
  hiro:
    full_name: 二阶堂希罗
    emotion_count: 6
    font: font3.ttf
    "无感情": [1]
    "愤怒": [6]
    "嫌弃": [1,3,4]
    "疑惑": [5]
    "惊讶": [5]
    "伤心": [4]
    "害羞": [2,3]
    "开心": [1,4]
    "恐惧": [6]
    "无语": [4]
    "大笑": [1]
  sherri:
    full_name: 橘雪莉
    emotion_count: 7
    font: font3.ttf
    "无感情": [3,5]
    "愤怒": [1]
    "嫌弃": [5]
    "疑惑": [5,7]
    "惊讶": [5,7]
    "伤心": [2,5]
    "害羞": [4,5]
    "开心": [3,6]
    "恐惧": [2,5,7]
    "无语": [1,4,5,7]
    "大笑": [3,6]
  hanna:
    full_name: 远野汉娜
    emotion_count: 5
    font: font3.ttf
    "无感情": [1,4]
    "愤怒": [1]
    "嫌弃": [1,4,3]
    "疑惑": [1,3,5]
    "惊讶": [1,5]
    "伤心": [2,3]
    "害羞": [2,3,5]
    "开心": [4]
    "恐惧": [5]
    "无语": [1,4]
    "大笑": [4]
  anan:
    full_name: 夏目安安
    emotion_count: 9
    font: font3.ttf
    "无感情": [1,4,7]
    "愤怒": [7]
    "嫌弃": [1,7,9]
    "疑惑": [3,5,7]
    "惊讶": [3,5,7]
    "伤心": [7,9]
    "害羞": [2,4,6,8]
    "开心": [2,4,6,8]
    "恐惧": [3,7,9]
    "无语": [1,3,7,9]
    "大笑": [4]
  yuki:
    full_name: 月代雪
    emotion_count: 18
    font: font3.ttf
    "无感情": [1,13,16,17,18]
    "愤怒": [11,13,15,18]
    "嫌弃": [8,10,11,13,14,17]
    "疑惑": [8,18]
    "惊讶": [8,11,14,15]
    "伤心": [17]
    "害羞": [1,3,5,6,8,13,14,15]
    "开心": [1,2,3,7,10,16,17,18]
    "恐惧": [14,15]
    "无语": [11,13,14,17]
    "大笑": [2,10]
  meruru:
    full_name: 冰上梅露露
    emotion_count: 6
    font: font3.ttf
    "无感情":
    "愤怒":
    "嫌弃":
    "疑惑":
    "惊讶":
    "伤心":
    "害羞":
    "开心":
    "恐惧":
    "无语":
    "大笑":
  noa:
    full_name: 城崎诺亚
    emotion_count: 6
    font: font3.ttf
    "无感情":
    "愤怒":
    "嫌弃":
    "疑惑":
    "惊讶":
    "伤心":
    "害羞":
    "开心":
    "恐惧":
    "无语":
    "大笑":
  reia:
    full_name: 莲见蕾雅
    emotion_count: 7
    font: font3.ttf
    "无感情":
    "愤怒":
    "嫌弃":
    "疑惑":
    "惊讶":
    "伤心":
    "害羞":
    "开心":
    "恐惧":
    "无语":
    "大笑":
  miria:
    full_name: 佐伯米莉亚
    emotion_count: 4
    font: font3.ttf
    "无感情":
    "愤怒":
    "嫌弃":
    "疑惑":
    "惊讶":
    "伤心":
    "害羞":
    "开心":
    "恐惧":
    "无语":
    "大笑":
  nanoka:
    full_name: 黑部奈叶香
    emotion_count: 5
    font: font3.ttf
    "无感情":
    "愤怒":
    "嫌弃":
    "疑惑":
    "惊讶":
    "伤心":
    "害羞":
    "开心":
    "恐惧":
    "无语":
    "大笑":
  mago:
    full_name: 宝生玛格
    emotion_count: 5
    font: font3.ttf
    "无感情":
    "愤怒":
    "嫌弃":
    "疑惑":
    "惊讶":
    "伤心":
    "害羞":
    "开心":
    "恐惧":
    "无语":
    "大笑":
  alisa:
    full_name: 紫藤亚里沙
    emotion_count: 6
    font: font3.ttf
    "无感情":
    "愤怒":
    "嫌弃":
    "疑惑":
    "惊讶":
    "伤心":
    "害羞":
    "开心":
    "恐惧":
    "无语":
    "大笑":
  coco:
    full_name: 泽渡可可
    emotion_count: 5
    font: font3.ttf
    "无感情":
    "愤怒":
    "嫌弃":
    "疑惑":
    "惊讶":
    "伤心":
    "害羞":
    "开心":
    "恐惧":
    "无语":
    "大笑":
# 在下方添加新角色信息，依次为全名、表情差分数量、使用字体
# 如：
#   warden:
#     full_name: 典狱长
#     emotion_count: 1
#     font: font3.ttf
#     "无感情":
#     "愤怒":
#     "嫌弃":
#     "疑惑":
#     "惊讶":
#     "伤心":
#     "害羞":
#     "开心":
#     "恐惧":
#     "无语":
#     "大笑":