darwin:
  character_1: <ctrl>+1
  character_2: <ctrl>+2
  character_3: <ctrl>+3
  character_4: <ctrl>+4
  character_5: <ctrl>+5
  character_6: <ctrl>+6
  
  prev_background: <ctrl>+i
  next_background: <ctrl>+k
  prev_character: <ctrl>+j
  next_character: <ctrl>+l
  prev_emotion: <ctrl>+u
  next_emotion: <ctrl>+o

  pause: <ctrl>+r
  quit: <ctrl>+q
  delete_cache: <ctrl>+d
  start_generate: <ctrl>+enter
  toggle_listener: <alt>+<ctrl>+p
gui:
  font_family: SimSun
  font_size: 12
  quick_characters:
    character_1: ema
    character_2: hiro
    character_3: sherri
    character_4: ''
    character_5: ''
    character_6: ''
win32:
  character_1: ctrl+1
  character_2: ctrl+2
  character_3: ctrl+3
  character_4: ctrl+4
  character_5: ctrl+5
  character_6: ctrl+6
  
  prev_background: ctrl+i
  next_background: ctrl+k
  prev_emotion: ctrl+u
  next_emotion: ctrl+o
  prev_character: ctrl+j
  next_character: ctrl+l
  
  pause: ctrl+r
  quit: ctrl+q
  delete_cache: ctrl+d
  start_generate: ctrl+e
  toggle_listener: alt+ctrl+p
