# 热键配置文件
# pynput格式，参考：https://pynput.readthedocs.io/en/latest/keyboard.html#pynput.keyboard.Key

# Windows热键配置
# 注意: Windows系统中，Ctrl键使用<ctrl>表示，Alt键使用<alt>表示，Win键使用<cmd>表示
#     - 由于Windows系统机制，`<alt>`组合键可能无法正常使用
win32:
  # 角色切换
  switch_character:
    - key: "<ctrl>+<shift>+1"
      param: 1
    - key: "<ctrl>+<shift>+2"
      param: 2
    - key: "<ctrl>+<shift>+3"
      param: 3
    - key: "<ctrl>+<shift>+4"
      param: 4
    - key: "<ctrl>+<shift>+5"
      param: 5
    - key: "<ctrl>+<shift>+6"
      param: 6
    - key: "<ctrl>+<shift>+7"
      param: 7
    - key: "<ctrl>+<shift>+8"
      param: 8
    - key: "<ctrl>+<shift>+9"
      param: 9
    - key: "<ctrl>+<shift>+q"
      param: 10
    - key: "<ctrl>+<shift>+e"
      param: 11
    - key: "<ctrl>+<shift>+r"
      param: 12
    - key: "<ctrl>+<shift>+t"
      param: 13
    - key: "<ctrl>+<shift>+y"
      param: 14
  # 显示当前角色
  show_current_character: "<ctrl>+<shift>+0"

  # 表情切换
  get_expression:
    - key: "<ctrl>+<alt>+1"
      param: 1
    - key: "<ctrl>+<alt>+2"
      param: 2
    - key: "<ctrl>+<alt>+3"
      param: 3
    - key: "<ctrl>+<alt>+4"
      param: 4
    - key: "<ctrl>+<alt>+5"
      param: 5
    - key: "<ctrl>+<alt>+6"
      param: 6
    - key: "<ctrl>+<alt>+7"
      param: 7
    - key: "<ctrl>+<alt>+8"
      param: 8
    - key: "<ctrl>+<alt>+9"
      param: 9

  # 启动生成
  start_generate: "<ctrl>+e"
  # 删除缓存
  delete_cache: "<ctrl>+d"
  # 退出程序
  quit: "<esc>"
  # 暂停/继续
  pause: "<ctrl>+r"


# macOS热键配置
# 注意: `<cmd>`表示Command键，`<ctrl>`表示Control键，`<alt>`表示Option键
darwin:
  # 角色切换
  switch_character:
    - key: "<ctrl>+<shift>+1"
      param: 1
    - key: "<ctrl>+<shift>+2"
      param: 2
    - key: "<ctrl>+<shift>+3"
      param: 3
    - key: "<ctrl>+<shift>+4"
      param: 4
    - key: "<ctrl>+<shift>+5"
      param: 5
    - key: "<ctrl>+<shift>+6"
      param: 6
    - key: "<ctrl>+<shift>+7"
      param: 7
    - key: "<ctrl>+<shift>+8"
      param: 8
    - key: "<ctrl>+<shift>+9"
      param: 9
    - key: "<ctrl>+<shift>+q"
      param: 10
    - key: "<ctrl>+<shift>+e"
      param: 11
    - key: "<ctrl>+<shift>+r"
      param: 12
    - key: "<ctrl>+<shift>+t"
      param: 13
    - key: "<ctrl>+<shift>+y"
      param: 14

  # 显示当前角色
  show_current_character: "<ctrl>+<shift>+0"

  # 表情切换 (Alt+数字键)
  get_expression:
    - key: "<ctrl>+<alt>+1"
      param: 1
    - key: "<ctrl>+<alt>+2"
      param: 2
    - key: "<ctrl>+<alt>+3"
      param: 3
    - key: "<ctrl>+<alt>+4"
      param: 4
    - key: "<ctrl>+<alt>+5"
      param: 5
    - key: "<ctrl>+<alt>+6"
      param: 6
    - key: "<ctrl>+<alt>+7"
      param: 7
    - key: "<ctrl>+<alt>+8"
      param: 8
    - key: "<ctrl>+<alt>+9"
      param: 9

  # 功能键
  start_generate: "<cmd>+e"
  delete_cache: "<ctrl>+d"
  quit: "<esc>"
  pause: "<ctrl>+<cmd>+r"